version: 1.0.{build}
image: Visual Studio 2017
build_script:
- ps: >-
    dotnet restore;
    dotnet build -c Release;
test_script:
- ps: ./ps/test_script.ps1
on_success:
- ps: ./ps/on_success.ps1
artifacts:
- path: Davenport/bin/Release/netstandard1.6
  name: netstandard16
- path: Davenport/bin/Release/net461
  name: net461