version: 1.0.{build}
image: Visual Studio 2017
build_script:
- ps: ./ps/build_script.ps1
test_script:
- ps: ./ps/test_script.ps1
artifacts:
- path: Davenport/bin/Release/netstandard1.4
  name: netstandard14
- path: Davenport/bin/Release/net461
  name: net461
skip_commits:
  message: /\[skip\]/
  files:
    - README.md
    - LICENSE
    - .gitignore
    - .vscode/*
    - changelog.md
deploy:
- provider: NuGet
  api_key:
    secure: uUJ91Fu+H69EdZ8RTYIa7G7UufCgCw1UXfZ2jAOEWJfKi8KNwDTFYaEDQCJS9xOc
  on:
    branch: master
    appveyor_repo_tag: true
- provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  description: "Automated AppVeyor release for Davenport v$(APPVEYOR_REPO_TAG_NAME). Check [changelog.md](https://github.com/nozzlegear/davenport.net/blob/master/changelog.md) for a list of changes."
  auth_token:
    secure: OS2yhg1H8KSYenGLlIIvVgsxU1xjtmNRjxrUBuwiWltI3JlvTmaBFijVINnGclbp
  artifact: davenport.nupkg
  on:
    branch: master
    appveyor_repo_tag: true