version: 1.0.{build}
image: Visual Studio 2017
build_script:
- ps: >-
    dotnet restore;
    dotnet build -c Release;
test_script:
- ps: >-
    curl https://dl.bintray.com/apache/couchdb/win/2.0.0.1/apache-couchdb-2.0.0.1.msi -UseBasicParsing -outfile couchdb.msi;
    install-package -providername msi ./couchdb.msi;

    $couchOutput = curl http://localhost:5984 -UseBasicParsing;
    
    if ($couchOutput.StatusCode -ne 200) {
        echo $couchOutput;
        throw "CouchDB did not return a 200 OK status code. Did it fail to install?";
    }

    function checkLastOutput ($output, $testName) {
        echo $output;

        if ($LastExitCode -ne 0 -or $output -contains "Test Run Failed.") {
            throw "$testName tests failed with exit code $LastExitCode.";
        }
    }

    $testProj = "Davenport.Tests/Davenport.Tests.csproj";
    $configTests = dotnet test -c Release $testProj --filter DisplayName~Config;

    checkLastOutput $configTests "Config";

    $clientTests = dotnet test $testProj -c Release --filter DisplayName~Client;

    checkLastOutput $clientTests "Client";
on_success:
- ps: dotnet pack --no-build -c Release Davenport/davenport.csproj;
artifacts:
- path: Davenport/bin/Release/*.nupkg
  name: nupkg
- path: Davenport/bin/Release/netstandard1.6
  name: netstandard16
- path: Davenport/bin/Release/net461
  name: net461